### ISSUE TITLE
powrap chokes on non-ascii characters on Windows

### ISSUE THREAD

**Issue by deronnax** [JulienPalard/powrap#1]
Calling powrap on a translated file gives the error below. It chokes on the first accentuated characters before giving up. Calling directly msgcat from the Windows shell works.
It might be something like Python subprocess.Popen function is feeding the msgcat subprocess with native Windows encoding (which something like utf-16) instead of utf-8. Passing `encoding='utf-8'` to `subprocess.run` fixes it **BUT** I can not garante yet it will not break another platform.

```
Fixing indentation in po files:   0%|          | 0/1 [00:00<?, ?it/s]<stdin>:37:25: invalid multibyte sequence
<stdin>:37:26: invalid multibyte sequence
<stdin>:38:26: invalid multibyte sequence
<stdin>:38:28: invalid multibyte sequence
<stdin>:38:29: invalid multibyte sequence
<stdin>:38:46: invalid multibyte sequence
<stdin>:38:47: invalid multibyte sequence
<stdin>:38:50: invalid multibyte sequence
<stdin>:38:51: invalid multibyte sequence
<stdin>:38:55: invalid multibyte sequence
<stdin>:38:56: invalid multibyte sequence
<stdin>:38:64: invalid multibyte sequence
<stdin>:38:65: invalid multibyte sequence
<stdin>:40:14: invalid multibyte sequence
<stdin>:40:15: invalid multibyte sequence
<stdin>:48:37: invalid multibyte sequence
<stdin>:48:38: invalid multibyte sequence
<stdin>:49:6: invalid multibyte sequence
<stdin>:49:7: invalid multibyte sequence
<stdin>:49:29: invalid multibyte sequence
msgcat: too many errors, aborting

Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mdupuy\AppData\Roaming\Python\Python36\Scripts\powrap.exe\__main__.py", line 9, in <module>
  File "C:\Users\mdupuy\AppData\Roaming\Python\Python36\site-packages\powrap\powrap.py", line 56, in main
    fix_style(args.po_files, args.modified, args.no_wrap)
  File "C:\Users\mdupuy\AppData\Roaming\Python\Python36\site-packages\powrap\powrap.py", line 33, in fix_style
    run(args, universal_newlines=True, check=True, input=po_content)
  File "c:\program files\python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['msgcat', '-', '-o', 'faq/design.po']' returned non-zero exit status 1.
```

**Comment by JulienPalard** [comment]
As we're already forcing utf-8 while reading the file, I'm ok to force utf8 while running subprocess.

Fixed in 0.2.1, thanks for reporting.
