### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by Jighdan** [JulienPalard/powrap#61]
```bash
Traceback (most recent call last):
  File "/home/jighdan/github/env/bin/powrap", line 8, in <module>
    sys.exit(main())
  File "/home/jighdan/github/env/lib/python3.8/site-packages/powrap/powrap.py", line 125, in main
    fix_style(args.po_files, args.no_wrap, args.quiet)
  File "/home/jighdan/github/env/lib/python3.8/site-packages/powrap/powrap.py", line 45, in fix_style
    run(args, encoding="utf-8", check=True, input=po_content)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'msgcat'
```

I have used different environment managers (`venv` and `conda`), install `powrap` from source; but still getting the same error.

**Comment by JulienPalard** [comment]
Hi @Jighdan, thanks for reporting!

`powrap` does not wrap itself, it's only a wapper using `msgcat` from `gettext`, so just `apt install gettext` (or whatever package manager you use), and tell me if it's better.
